name: PlayerKitDemo
options:
  bundleIdPrefix: com.ljx
  deploymentTarget:
    iOS: "15.6"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
packages:
  BizPlayerKit:
    path: ../Packages/BizPlayerKit
  MixedListKit:
    path: ../Packages/MixedListKit
targets:
  PlayerKitDemo:
    type: application
    platform: iOS
    sources:
      - PlayerKitDemo
    dependencies:
      - package: BizPlayerKit
      - package: MixedListKit
    settings:
      base:
        INFOPLIST_FILE: PlayerKitDemo/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.ljx.playerkitdemo
        TARGETED_DEVICE_FAMILY: "1"
        SWIFT_VERSION: "5.0"
  BizPlayerKitTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - ../Packages/BizPlayerKit/Tests/BizPlayerKitTests
    dependencies:
      - package: BizPlayerKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ljx.bizplayerkit.tests
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_VERSION: "5.0"
        GENERATE_INFOPLIST_FILE: YES
